[Log]
  PATH = ""
  PREFIX = "Chapper"

[Turn]
  PUBLIC_IP = ""
  PORT = 0

[Store]
  USER = "root"
  PASSWORD = "root"
  DATABASE = "chapper"
  HOST = "127.0.0.1"
  PORT = 3306

[Router]
  PORT = 8080
  DOMAIN = "chapper.localhost"
  WEB_PATH = ""
  AVATAR_PATH = ""
  JWT_SIGNING_KEY = ""
  OTP_ISSUER = "Chapper"
  ENABLE_GZIP = true

[General]
  NAME = "Chapper"
  ENABLE_REGISTER = true
  DISABLE_BANNER = false
